EVENT_DATA_FIELDS = [
    "food_made",
    "food_used",
    "minerals_collection_rate",
    "minerals_lost",
    "minerals_lost_army",
    "minerals_used_current",
    "minerals_used_current_army",
    "minerals_used_current_economy",
    "vespene_collection_rate",
    "vespene_lost",
    "vespene_lost_army",
    "vespene_used_current",
    "vespene_used_current_army",
    "vespene_used_current_economy",
    "vespene_used_current_technology",
    "workers_active_count",
]
